services:
    protonvpn:
        image: docker.io/qmcgaw/gluetun:latest
        container_name: protonvpn
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        env_file: .env
        environment:
            - TZ=${TZ}
            - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
            - VPN_TYPE=${VPN_TYPE}
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
            - SERVER_COUNTRIES=${SERVER_COUNTRIES}
            - PORT_FORWARD_ONLY=on
            - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
        volumes:
            - ./vpn:/gluetun
        ports:
            - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        depends_on:
            - protonvpn
        env_file: .env
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
        volumes:
            - ./config:/config
            - ${PATH_MEDIA}:/downloads
        network_mode: "service:protonvpn"
        restart: unless-stopped
