version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9075:9075" # Porta de controle HTTP do Gluetun
      - "8085:8085" # Porta do qBittorrent WebUI
      - "8096:8096" # Porta do Jellyfin
      - "8920:8920" # Porta do Jellyfin HTTPS
      - "1900:1900/udp" # DLNA do Jellyfin
      - "7359:7359/udp" # Descoberta do Jellyfin
    volumes:
      - ./config/gluetun:/gluetun
      - ./config/gluetun/tmp:/tmp/gluetun # Para port forwarding
    environment:
      - TZ=America/Sao_Paulo
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WG_ADDRESSES}
      - WIREGUARD_PUBLIC_KEY=${WG_PUBLIC_KEY}
      - VPN_PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=172.16.0.0/12,192.168.0.0/16
      - HTTP_CONTROL_SERVER_ADDRESS=:9075
      - HTTPCONTROL_SERVER_LOG=true
    healthcheck:
      test: ["CMD", "/gluetun/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8085
    volumes:
      - ./config/qbittorrent:/config
      - /srv/media/downloads:/downloads # Pasta de downloads temporários
      - /srv/media:/media:shared # Pasta compartilhada para organização final
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/jellyfin:/config
      - ./config/jellyfin/cache:/cache
      - /srv/media:/media:shared # Mesma pasta compartilhada do qBittorrent
    devices:
      - /dev/dri:/dev/dri # Para aceleração de hardware (se disponível)
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  gluetun-qbittorrent-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:latest
    container_name: gluetun-qbittorrent-port-manager
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - QBITTORRENT_SERVER=localhost
      - QBITTORRENT_PORT=8085
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASS=${QBIT_PASSWORD}
      - PORT_FORWARDED=/tmp/gluetun/forwarded_port
      - HTTP_S=http
    volumes:
      - ./config/gluetun/tmp:/tmp/gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
