name: Validate Docker Compose

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose.yml
        run: docker compose config

