name: Validate Docker Compose

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Find and validate all docker-compose files
        run: |
          # Encontra todos os docker-compose.yml e docker-compose.override.yml
          files=$(find . -type f -name 'docker-compose*.yml')
          
          if [ -z "$files" ]; then
            echo "Nenhum arquivo docker-compose encontrado."
            exit 1
          fi
          
          for f in $files; do
            echo "Validando $f..."
            docker compose -f "$f" config
          done
